// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void formTest() {
    driver.get("http://sampleapp.tricentis.com/101/app.php");
    driver.manage().window().setSize(new Dimension(1296, 1040));
    driver.findElement(By.id("make")).click();
    {
      WebElement dropdown = driver.findElement(By.id("make"));
      dropdown.findElement(By.xpath("//option[. = 'BMW']")).click();
    }
    driver.findElement(By.id("engineperformance")).click();
    driver.findElement(By.id("engineperformance")).sendKeys("100");
    driver.findElement(By.id("opendateofmanufacturecalender")).click();
    {
      WebElement element = driver.findElement(By.id("opendateofmanufacturecalender"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.id("numberofseats")).click();
    {
      WebElement dropdown = driver.findElement(By.id("numberofseats"));
      dropdown.findElement(By.xpath("//option[. = '2']")).click();
    }
    driver.findElement(By.cssSelector(".idealsteps-step:nth-child(1)")).click();
    driver.findElement(By.id("fuel")).click();
    {
      WebElement dropdown = driver.findElement(By.id("fuel"));
      dropdown.findElement(By.xpath("//option[. = 'Gas']")).click();
    }
    driver.findElement(By.id("listprice")).click();
    driver.findElement(By.id("listprice")).sendKeys("32000");
    driver.findElement(By.id("licenseplatenumber")).click();
    driver.findElement(By.id("licenseplatenumber")).sendKeys("123");
    driver.findElement(By.id("annualmileage")).click();
    driver.findElement(By.id("annualmileage")).sendKeys("100");
    driver.findElement(By.id("nextenterinsurantdata")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Robert");
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("Silva");
    driver.findElement(By.id("opendateofbirthcalender")).click();
    driver.findElement(By.linkText("1")).click();
    driver.findElement(By.cssSelector(".group:nth-child(2) > .ideal-radiocheck-label:nth-child(1) > .ideal-radio")).click();
    driver.findElement(By.id("streetaddress")).click();
    driver.findElement(By.id("streetaddress")).sendKeys("Rua A");
    driver.findElement(By.id("country")).click();
    {
      WebElement dropdown = driver.findElement(By.id("country"));
      dropdown.findElement(By.xpath("//option[. = 'Burundi']")).click();
    }
    driver.findElement(By.id("zipcode")).click();
    driver.findElement(By.id("zipcode")).sendKeys("32659");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("occupation")).click();
    {
      WebElement dropdown = driver.findElement(By.id("occupation"));
      dropdown.findElement(By.xpath("//option[. = 'Employee']")).click();
    }
    driver.findElement(By.cssSelector(".field:nth-child(10) .ideal-radiocheck-label:nth-child(1) > .ideal-check")).click();
    driver.findElement(By.cssSelector(".valid .ideal-radiocheck-label:nth-child(2) > .ideal-check")).click();
    driver.findElement(By.cssSelector(".ideal-radiocheck-label:nth-child(5) > .ideal-check")).click();
    driver.findElement(By.id("website")).click();
    driver.findElement(By.id("nextenterproductdata")).click();
    driver.findElement(By.id("openstartdatecalender")).click();
    driver.findElement(By.linkText("5")).click();
    driver.findElement(By.cssSelector("#openstartdatecalender > .fa")).click();
    driver.findElement(By.linkText("13")).click();
    driver.findElement(By.cssSelector("#openstartdatecalender > .fa")).click();
    driver.findElement(By.linkText("4")).click();
    driver.findElement(By.id("openstartdatecalender")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-next")).click();
    driver.findElement(By.linkText("18")).click();
    driver.findElement(By.id("insurancesum")).click();
    {
      WebElement dropdown = driver.findElement(By.id("insurancesum"));
      dropdown.findElement(By.xpath("//option[. = '10.000.000,00']")).click();
    }
    driver.findElement(By.id("meritrating")).click();
    {
      WebElement dropdown = driver.findElement(By.id("meritrating"));
      dropdown.findElement(By.xpath("//option[. = 'Malus 10']")).click();
    }
    driver.findElement(By.id("damageinsurance")).click();
    {
      WebElement dropdown = driver.findElement(By.id("damageinsurance"));
      dropdown.findElement(By.xpath("//option[. = 'Partial Coverage']")).click();
    }
    driver.findElement(By.cssSelector(".field:nth-child(5) .ideal-radiocheck-label:nth-child(1) > .ideal-check")).click();
    driver.findElement(By.id("courtesycar")).click();
    {
      WebElement dropdown = driver.findElement(By.id("courtesycar"));
      dropdown.findElement(By.xpath("//option[. = 'Yes']")).click();
    }
    driver.findElement(By.id("nextselectpriceoption")).click();
    driver.findElement(By.id("selectpriceoption")).click();
    driver.findElement(By.cssSelector("#xLoaderPrice span:nth-child(3)")).click();
    driver.findElement(By.id("enterproductdata")).click();
    driver.findElement(By.id("enterinsurantdata")).click();
    driver.findElement(By.id("opendateofbirthcalender")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-title")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-prev")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-prev")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-prev")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-prev")).click();
    driver.findElement(By.linkText("2")).click();
    driver.findElement(By.id("opendateofbirthcalender")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-month")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-title")).click();
    driver.findElement(By.cssSelector(".ui-datepicker-title")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-datepicker-title"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("birthdate")).click();
    driver.findElement(By.id("birthdate")).click();
    {
      WebElement element = driver.findElement(By.id("birthdate"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("birthdate")).sendKeys("06/02/1993");
    driver.findElement(By.cssSelector(".idealsteps-step:nth-child(2)")).click();
    driver.findElement(By.id("selectpriceoption")).click();
    driver.findElement(By.cssSelector(".choosePrice:nth-child(2) > .ideal-radio")).click();
    driver.findElement(By.id("nextsendquote")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("email@email.com");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("RobertSilva");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("HMs125");
    driver.findElement(By.id("confirmpassword")).click();
    driver.findElement(By.id("confirmpassword")).sendKeys("HMs123");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.id("password"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("HMs123");
    driver.findElement(By.id("Comments")).click();
    driver.findElement(By.id("sendemail")).click();
    {
      WebElement element = driver.findElement(By.id("sendemail"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Sending e-mail success!"));
    driver.findElement(By.cssSelector(".confirm")).click();
  }
}
